# Generated by Django 3.0 on 2022-02-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signbook',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
